{% set version = "0.9.0" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}

package:
  name: symengine
  version: {{ version }}

source:
  url: https://github.com/symengine/symengine/releases/download/v{{ version }}/symengine-{{ version }}.tar.gz
  sha256: dcf174ac708ed2acea46691f6e78b9eb946d8a2ba62f75e87cf3bf4f0d651724

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - make             # [unix]
    - ninja            # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gmp              # [unix]
    - mpir             # [win]
    - mpfr
    - mpc
    - llvmdev
    - zlib
    - libflint
  run:
    - gmp              # [unix]
    - mpir             # [win]
    - mpfr
    - mpc
    - libflint

test:
  commands:
    - if not exist %LIBRARY_INC%\\symengine\\basic.h exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\symengine.lib exit 1          # [win]
    - if not exist %LIBRARY_BIN%\\symengine-{{ maj_min }}.dll exit 1          # [win]
    - test -f $PREFIX/include/symengine/basic.h                 # [unix]
    - test -f $PREFIX/lib/libsymengine.so                       # [linux]
    - test -f $PREFIX/lib/libsymengine.dylib                    # [osx]

about:
  home: https://github.com/symengine/symengine
  license: MIT
  license_file: LICENSE
  summary: SymEngine is a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
