travis:
  secure:
    BINSTAR_TOKEN: NFdgzHHjbc+cItr/KKqqDVYmuIxRZ5SPSAsu3x5ozhf84pd9vRSl1qY6eYXo1KmQjfybMH3l+6IaDiWcWo5j8BDTg2rzZCmmPTOcn1aKdMmHuKJ9j2Mp0HuHvL3/HuEAPDUFXVfQHpZmLjdNzugNbtLzriMxGx1gkXWwP5m8wmrG1GGQxz85dh28qNVoL1Ge4s9i1+hHubam8qSOsGetfprxE4Zpp/3lc5phtbv8MJ9ep2J+g9+GBzx00vRpSWc7Yk9gEHjT9n3+wxVtZ3Kh1L/vV1+2T6Ez3I6TQoPWXX2JrvUsecCAr87iDCwPBKQjpoqLFwc/qDV6BeMGT5FgXZ+3jUc2Psj9bhq1BT8efVuXsDksbfiG1/60++s80g898mGtT5veTd5OJWMzN2YTOpoAvWyN6hVe03fBKf0cY8PTA1L9xNINLFbA3WDZaG41N47H1H/bWcwgE1w/tiAzkGYojZTCAdBIcs6g0pk+jp1J+/sv0aZRaWV2QBpp74WIATpVvip9JvJCySS0QDJxSyRxAwnYl/+IvGfIfZ+OzVy+AMVKC3LBjJr261Wmpe1aUv1Spcch6MZtqb00C8o5oDdP+VDvJBvoU1Wwfrfn1yriqAV+7s//P7Blvr8wyhgLQc2nFlaBuS7hqrFUeb++o9N4xvE6/MOn0dPDKRALl6E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
