travis:
  secure:
    BINSTAR_TOKEN: kkIMHbl7RYe0nEt2VkvBXsm+UXSFeJd3VJM/jDkyNVS5K0HuU55WdyWlYx8iCm7XIBe3ALKNhi1A/b5CXmaIOUbt+gQqr8fZkWQ3ap3DuLu/O7dQISYGYsA6C2iAiJ4X6E50bs+58MB7TMCTDGziaH9HwNP3L1AwfZCI4i9cnnxMijtc1S9buIcebBFG81CGRwjr4sNsXraWcJY4bfPSASDD87DEKviIUGkA5RY+trGGJvGrqeY+s62DdytDsT6rigM1zJJ3uNJ+ZudT4MF8bLcTPXbDzQoBx4To9uSUpl378oYZZaxmJxI61eHR47zHuiThJcXrnegYL1QKeqXSQEMf5Pm/3VQ8Rc/l+529dTDuQGfsr8XkHQ3l9+vsD9gyGxpGbLX6CsimoGuDCCp9xvbn7CL102gA5Zut3BJsUX1d4Ehta+e7FklQg1HtPCpeXUygP8JrC0Or6wFGuffXQSXdeH2sy9Vzx0k1vv3DpOODpqgYTwakzS4tMRYFqnVq/I/qAfCM59ZHS/87RyI/mapFv68abx3YErpoNdr8UBiXrB1Ot5dvOagr0W3X6mS1uDZHOZGIz6YusO1rUnOWaKPpZIG73zI8wJMI+gC5bJhwAesa3trnI0vVrmErH3TPfdR1z8VV/c2BIytmQeWRubF25+h0HB+DaxYm6Q/++8o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
